try{
	dir('tt')
} catch(err){
	log('exception thrown '+err)
}
